name: Tests

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      RABBITMQ_URI: amqp://guest:guest@localhost:5672
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      KONSI_BASE_URL: http://localhost:8000
      ELASTIC_API_URL: http://localhost:9200
      NODE_ENV: test
      KONSI_USERNAME: test
      KONSI_PASSWORD: test
      REDIS_TOKEN_KEY: konsi:token_test
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
          - 15672:15672
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '23.3.0'
          architecture: 'x64'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Test Suite
        run: npm run test